#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MonocleGiraffe.Android.Resource", IsApplication=true)]

namespace MonocleGiraffe.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int typeface = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int Gray = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ImgurGreen = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001d
			public const int AddButton = 2131099677;
			
			// aapt resource value: 0x7f060016
			public const int AlbumRecyclerView = 2131099670;
			
			// aapt resource value: 0x7f060000
			public const int BrowserPager = 2131099648;
			
			// aapt resource value: 0x7f06001e
			public const int CheckButton = 2131099678;
			
			// aapt resource value: 0x7f060019
			public const int CommentsTextView = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int DescriptionTextView = 2131099675;
			
			// aapt resource value: 0x7f060010
			public const int EditText = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int GalleryRecyclerView = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int GifsButton = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int HelloTextView = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int LayoutRoot = 2131099649;
			
			// aapt resource value: 0x7f060011
			public const int LogInButton = 2131099665;
			
			// aapt resource value: 0x7f06001a
			public const int MainImage = 2131099674;
			
			// aapt resource value: 0x7f060003
			public const int MainImageView = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int MainPager = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int MainVideoView = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int PostsButton = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int QueryEditText = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int RedditsButton = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int ResultsFrame = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int ResultsRecyclerView = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int SubGalleryRecyclerView = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int SubTitleTextView = 2131099669;
			
			// aapt resource value: 0x7f06001c
			public const int SubtitleTextView = 2131099676;
			
			// aapt resource value: 0x7f060012
			public const int TextView = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int Thumbnail = 2131099671;
			
			// aapt resource value: 0x7f060014
			public const int TitleTextView = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int UpsTextView = 2131099672;
			
			// aapt resource value: 0x7f060006
			public const int UserNameTextView = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int reddits_header = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int reddits_list = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Browser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Ctrl_Image = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Front = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Front_Account = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Front_Gallery = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Front_Reddits = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Front_Search = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SubGallery = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Tmpl_Album = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Tmpl_GalleryThumbnail = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Tmpl_Image = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Tmpl_Item_Album = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Tmpl_SubredditItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Tmpl_SubredditResult = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Tmpl_SubredditThumbnail = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int ApplicationName = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int Get = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int Log_In = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Save = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int TF_Material = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontTextView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int FontTextView_typeface = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
